# Template for Kubernetes secrets
# DO NOT commit actual secrets to version control
# Copy this file to secrets.yaml and fill in the base64-encoded values
apiVersion: v1
kind: Secret
metadata:
  name: pactwise-secrets
  namespace: pactwise
type: Opaque
data:
  # Base64 encode your values: echo -n "your-value" | base64
  convex-url: <base64-encoded-convex-url>
  clerk-publishable-key: <base64-encoded-clerk-publishable-key>
  clerk-secret-key: <base64-encoded-clerk-secret-key>
  sentry-dsn: <base64-encoded-sentry-dsn>
  redis-url: <base64-encoded-redis-url> # Optional
  
# Example encoding:
# echo -n "https://your-project.convex.cloud" | base64
# echo -n "pk_test_your-clerk-key" | base64